Now it's turn  of file c.... 
where some new text has been entered....
The text starts here.... 
...
......
........
and 'ends' here....!!
....
some additional text is being added in file 'c'
starting from here....
.
..
....
...
.....
and 'ending' here....!!
